print("this level would be easy at you")
print("so lets start")
print("hej = hello/hi")
print("tak = thanku")
print("farval = goodbye")
print("ja = yes")
print("nej = no")
print("ven = friend")
print("remainder: nej means no and hej means hello dont get confused")