print("You have came again to prove yourself")
print("never mind")
print("here are your words")
print("Familie = family")
print("kat = cat")
print("hund = dog")
print("hus = house")
print("venner = friends")
print("what you learn them!")
print("lets take a short quiz of you in the next level")